# settings.yaml
data:
  data_path: "my_data.csv"
  symbol_list: [ "AAPL", "GOOG" ]
  price_adjustment: "hfq"

trading:
  initial_cash: 100000
  commission_rate: 0.001
  slippage: 0.0005
  limit_up_down_buffer: 0.01
  risk_pct: 0.01

  symbol_list:
    - "000001.SZ"
    - "600519.SH"

execution:
  commission_rate: 0.0005
  limit_up_pct: 0.1
  limit_down_pct: 0.1

strategy:
  short_window: 10
  long_window: 30

ml:
  model_path: "trained_model.pkl"

  auto_save: true
  auto_load: true
  lookback: 30
  model_dir: "models"

database:
  db_uri: "localhost:6001"

system:
  api_key: "train_api_key"
  api_secret: "train_api_secret"
  mode: "train"

