name: Python package

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev-commission
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pip install -r requirements.txt
      - name: Test with Pytest
        run:  python -m pytest
