name: Post-Merge Tasks

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release on master
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ steps.date.outputs.date }}
          name: Release ${{ steps.date.outputs.date }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sync:
    name: Sync master → dev
    runs-on: ubuntu-latest
    needs: release

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0  # Fetch all branches

      - run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git fetch origin dev || echo "dev branch does not exist yet"

          # Create dev if it doesn't exist
          if ! git rev-parse origin/dev >/dev/null 2>&1; then
            echo "Creating dev branch from master"
            git checkout -b dev
            git push origin dev
          else
            git checkout dev
            git merge origin/master --no-ff --no-edit
            git push origin dev
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

