name: CI/CD Pipeline

on:
  push:
    branches:
      - 'dev'
      - 'dev-*'
  pull_request:
    branches:
      - 'dev'
      - 'master'

jobs:
  test:
    name: Run Tests with Pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest
        run: |
          pytest

  create-pr:
    name: Create PR dev → master
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/dev'
    outputs:
      pr_number: ${{ steps.cpr.outputs.pull-request-number }}

    steps:
      - name: Checkout dev
        uses: actions/checkout@v3
        with:
          ref: dev
          fetch-depth: 0

      - name: Create PR
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master
          branch: dev
          title: 'Auto PR: dev → master'
          body: |
            Auto-generated PR to merge dev into master after tests pass.
          commit-message: 'chore: auto PR dev → master'
          delete-branch: false

  auto-merge-pr:
    name: Enable Auto-Merge via gh CLI
    runs-on: ubuntu-latest
    needs: create-pr
    steps:
      - name: Checkout repo (required for .git)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Enable Auto-Merge via gh CLI
        run: |
          gh pr merge ${{ needs.create-pr.outputs.pr_number }} --auto --squash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

