name: CI/CD Pipeline

on:
  push:
    branches:
      - 'dev'
      - 'dev-*'
  pull_request:
    branches:
      - 'dev'
      - 'master'

jobs:
  test:
    name: Run Tests with Pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest
        run: |
          pytest --maxfail=1 --disable-warnings --cov

  auto-merge-dev-to-master:
    name: Auto Merge dev → master
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/dev')  # Only on push to dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git for GitHub Actions
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Merge dev into master
        run: |
          git fetch origin master
          git checkout master
          git merge origin/dev --no-ff --no-edit
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
