name: Merge on Test Pass

on:
  pull_request:
    branches: [ "dev" ] # Trigger only on PRs targeting the dev branch

jobs:
  test_and_merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run pytest
        run: pytest
      - name: Merge pull request
        if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'dev' && github.ref == 'refs/pull/${{ github.event.pull_request.number }}/merge'
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}
          mediaType: application/vnd.github.v3+json
          body: '{"state":"closed"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}