name: Test and Auto-Merge to Dev

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: |
          pytest

  automerge:
    needs: test
    if: ${{ github.event.pull_request.user.login != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge PR into dev
        uses: "peter-evans/auto-merge@v3"
        with:
          merge-method: squash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
